### ISSUE TITLE
옹 열일하시네용! 멋지십니당 

### ISSUE THREAD

**Issue by SeungYeon04** [lionleeee/typescript-TIL#1]
우앙 활동 좋으시구먼용 
뭔가 깃허브 들어올 때마다 위에 계셔용! 
온제나 화이팅입니다 멋지십니당⭐️ 
글고 프로필 펫 넘 귀여워요.. 줍줍할게요..🥺💕 
(저는 전주 비전대 강연 들은 학생입니당! 반갑습니다아)

**Comment by lionleeee** [comment]
LGTM👍
